apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bwy0eilw8-python
  janus-idp.io/tekton: bwy0eilw8-python
  backstage.io/kubernetes-id: bwy0eilw8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bwy0eilw8-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
